import type { Metadata } from "next";
import { Suspense } from "react";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { cn } from "@/lib/utils";

import { QueryProvider } from "@/components/query-providers";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={cn(inter.className,'antialiased min-h-screen')}>
        <QueryProvider>
          <Suspense fallback={null}>
            <NuqsAdapter>
              <Toaster />
              {children}
            </NuqsAdapter>
          </Suspense>
        </QueryProvider>
      </body>
    </html>
  );
}
